name: general
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - dav1d=1.2.1
  - expat=2.6.4
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - imageio=2.33.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtheora=1.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.6.0
  - openjpeg=2.5.2
  - openssl=3.0.18
  - pcre2=10.46
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.12.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - imageio-ffmpeg==0.6.0
      - psutil==6.1.1
